config/routes.rb
Rails.application.routes.draw do
  if defined?(Rswag::Ui::Engine)
    mount Rswag::Ui::Engine => "/api-docs"
    mount Rswag::Api::Engine => "/api-docs"
  end

  resources :users, only: [ :new, :create ]
  get    "login",  to: "sessions#new"
  post   "login",  to: "sessions#create"
  delete "logout", to: "sessions#destroy"

  resources :transactions
  # get "home/index"
  get "home/about", to: "home#about", as: :about
  root "home#index"

  post "transactions/convert", to: "transactions#convert", as: :convert_transactions
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
    @title = "About"
    @description = "This is the about page of our application."
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <%= link_to "Currency Converter", root_path, class:"navbar-brand" %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <%# <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li> %>
        
        <li class="nav-item">
          <%= link_to "About CurConv", about_path, class:"nav-link" %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1 class="text-center">About</h1>
<p>Find out more about our currency converter application and its features.</p>

app/views/home/index.html.erb
<h1 class="text-center">Currency Converter</h1>

<% if current_user %>
  <div class="d-grid gap-3">
    <p class="text-center">What do you want to do now?</p>

    <%= link_to "New Conversion", new_transaction_path, class: "btn btn-primary btn-lg" %>
    <%= link_to "See My Transactions", transactions_path, class: "btn btn-secondary btn-lg" %>
  </div>
<% end %>